### ISSUE TITLE
Fails to build on MSVC due to incorrect force include for .sycl file

### ISSUE THREAD

**Issue by AerialMantis** [KhronosGroup/SyclParallelSTL#1]
On MSVC the force include for the .sycl is incorrect so the examples fail to build correctly.

The cmake property for setting the force include file for MSVC needs to have the space removed after the /FI, so it should be like this instead:

/FI${CMAKE_CURRENT_BINARY_DIR}/${filename}.sycl ${CMAKE_CXX_FLAGS}")

**Comment by Ruyk** [comment]
This has been fixed on the latest merge.
