### ISSUE TITLE
Can't build the project on ubuntu 14.04, gcc 4.8 with ComputeCpp CE 0.1.2

### ISSUE THREAD

**Issue by babouFomb** [KhronosGroup/SyclParallelSTL#35]
Dear all,

I try to build the project on Ubuntu 14.04, gcc 4.8 with ComputeCpp.

I passed the following flags to cmake in order to build the project:
`cmake -DCOMPUTECPP_PACKAGE_ROOT_DIR=/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.1.2-Linux -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include -DPARALLEL_STL_BENCHMARKS=ON  ..` 

Cmake run without error. Then I run make, I get the following error:

> Scanning dependencies of target sycl_exclusive_scan_integration_header
[ 53%] Building ComputeCpp integration header file /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/build/benchmarks/sycl_exclusive_scan.cpp.sycl
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/benchmarks/sycl_exclusive_scan.cpp:36:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/include/sycl/execution_policy:48:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.1.2-Linux/include/CL/sycl.hpp:1:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.1.2-Linux/include/CL/../SYCL/sycl.hpp:20:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.1.2-Linux/include/SYCL/sycl_interface.h:135:
/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.1.2-Linux/include/SYCL/apis.h:902:9: error: [Computecpp:CC0004]: a SYCL kernel with the name class
      ExclusiveScanAlgorithm1 (alias typename detail::enable_functor<class (lambda at
      /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/include/sycl/algorithm/buffer_algorithms.hpp:514:43), class
      ExclusiveScanAlgorithm1>::kernel_name) already exists
        typename detail::enable_functor<functorT, nameT>::kernel_name,
        ^
/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.1.2-Linux/include/SYCL/apis.h:902:9: note: original SYCL kernel with name class
      ExclusiveScanAlgorithm1 (alias typename detail::enable_functor<class (lambda at
      /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/include/sycl/algorithm/buffer_algorithms.hpp:399:43), class
      ExclusiveScanAlgorithm1>::kernel_name) defined here
1 error generated.
make[2]: *** [benchmarks/sycl_exclusive_scan.cpp.sycl] Error 1
make[1]: *** [benchmarks/CMakeFiles/sycl_exclusive_scan_integration_header.dir/all] Error 2
make: *** [all] Error 2

**Comment by babouFomb** [comment]
Hi dear all, now I use computecpp latest realise (ComputeCpp-CE-0.2.1-Linux), but I get the same errors:

[ 53%] Building ComputeCpp integration header file /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/build/benchmarks/sycl_exclusive_scan.cpp.sycl
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/benchmarks/sycl_exclusive_scan.cpp:36:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/include/sycl/execution_policy:48:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.2.1-Linux/include/CL/sycl.hpp:1:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.2.1-Linux/include/CL/../SYCL/sycl.hpp:20:
In file included from /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.2.1-Linux/include/SYCL/sycl_interface.h:139:
/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.2.1-Linux/include/SYCL/apis.h:969:9: error: [Computecpp:CC0004]: a SYCL kernel with the name class
      ExclusiveScanAlgorithm1 (alias typename detail::enable_functor<class (lambda at
      /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/include/sycl/algorithm/buffer_algorithms.hpp:514:43), class
      ExclusiveScanAlgorithm1>::kernel_name) already exists
        typename detail::enable_functor<functorT, nameT>::kernel_name,
        ^
/home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/ComputeCpp-CE-0.2.1-Linux/include/SYCL/apis.h:969:9: note: original SYCL kernel with name class
      ExclusiveScanAlgorithm1 (alias typename detail::enable_functor<class (lambda at
      /home/rokiatou/Documents/Thèse/sycl_kronos/different_implementation_of_sycl/SyclParallelSTL/include/sycl/algorithm/buffer_algorithms.hpp:399:43), class
      ExclusiveScanAlgorithm1>::kernel_name) defined here
1 error generated.
make[2]: *** [benchmarks/sycl_exclusive_scan.cpp.sycl] Error 1
make[1]: *** [benchmarks/CMakeFiles/sycl_exclusive_scan_integration_header.dir/all] Error 2
make: *** [all] Error 2


Can anyone help me please?
Thanks.

**Comment by Ruyk** [comment]
Seems there is a duplicated kernel name, which means two kernels are being generated with the same name. This is likely an issue with the name generator of the algorithm, but for some reason is not failing on travis. @Zakor94  can you take a look into this? Seems your last patch didn't fix the previous problem with some routines.

**Comment by Ruyk** [comment]
Can you try with the issue-35 branch to see if this solves your problem? 
Changes are in: https://github.com/KhronosGroup/SyclParallelSTL/pull/36
Seems when we merged the triSYCL branch there were some errors, but travis has been misleading us!

**Comment by babouFomb** [comment]
Thanks, I tried with the issue-35 branch and the problem is solved. I compiled SyclParallelSTL without any errors.

**Comment by Zakor94** [comment]
It is very weird because I didn't need the NameGen for my tests.
And some of my changes seem to have disappeared. I added a comment to https://github.com/KhronosGroup/SyclParallelSTL/pull/36 even though it is already merged.
