### ISSUE TITLE
OpenCL CPU test is no longer working in Travis-CI

### ISSUE THREAD

**Issue by keryell** [KhronosGroup/SyclParallelSTL#69]
The Intel OpenCL CPU stack used to be used by Travis-CI but it looks like it is no longer available on-line in the way it was down=loaded automatically with https://github.com/KhronosGroup/SyclParallelSTL/blob/master/.travis/install_intel_opencl.sh from 
http://registrationcenter-download.intel.com/akdlm/irc_nas/12513/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz

**Comment by keryell** [comment]
@bashbaug is there an official way to use Intel CPU OpenCL implementation in some public continuous integration framework?

**Comment by bader** [comment]
@keryell, please, update the link to the Intel OpenCL CPU run-time: http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz

Correct link can be found at https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime.

**Comment by keryell** [comment]
Thank you @bader and @bashbaug for making the Khronos world brighter. :-)
I fixed this in https://github.com/KhronosGroup/SyclParallelSTL/pull/72
