### ISSUE TITLE
Wrong nd_item<> rank in nbody benchmarks

### ISSUE THREAD

**Issue by keryell** [KhronosGroup/SyclParallelSTL#78]
`benchmarks/nbody.cpp` cannot compile with triSYCL because there is a 3D kernel functor called from a 1D `parallel_for`.
Very curious that it compiles, runs and passes the test with ComputeCpp... What is the semantics?
I have fixed the example and the pull request is coming...

**Comment by Ruyk** [comment]
We don't make distinction between the dimensions internally, it will simply just work. It doesn't make any difference for us.
But thanks for fixing it, looking forward to accept the pull request!
